### ISSUE TITLE
关于harvest的逻辑

### ISSUE THREAD

**Issue by bwkong2077** [JesseTzh/ScreepsBoot#1]
您的代码看起来很棒！我有个问题，为什么不用container配合无carry组件的creep挖矿呢？Harvest采矿后掉落自动被container收集，仅由mover转运。这样效率似乎更高。
如果您的代码中有相应设置请麻烦告知一下，谢谢！

**Comment by JesseTzh** [comment]
这种方法在前期不失为一个好选择，但是后期总归要使用Link传输能量，这种方法适用时间有限，所以并没有添加

**Comment by JesseTzh** [comment]
> 您的代码看起来很棒！我有个问题，为什么不用container配合无carry组件的creep挖矿呢？Harvest采矿后掉落自动被container收集，仅由mover转运。这样效率似乎更高。
> 如果您的代码中有相应设置请麻烦告知一下，谢谢！
这种方法在前期不失为一个好选择，但是后期总归要使用Link传输能量，这种方法适用时间有限，所以并没有添加

**Comment by JesseTzh** [comment]
> 您的代码看起来很棒！我有个问题，为什么不用container配合无carry组件的creep挖矿呢？Harvest采矿后掉落自动被container收集，仅由mover转运。这样效率似乎更高。
> 如果您的代码中有相应设置请麻烦告知一下，谢谢！

这种方法在前期不失为一个好选择，但是后期总归要使用Link传输能量，适用时间有限，所以并没有添加

**Comment by bwkong2077** [comment]
> > 您的代码看起来很棒！我有个问题，为什么不用container配合无carry组件的creep挖矿呢？Harvest采矿后掉落自动被container收集，仅由mover转运。这样效率似乎更高。
> > 如果您的代码中有相应设置请麻烦告知一下，谢谢！
> 
> 这种方法在前期不失为一个好选择，但是后期总归要使用Link传输能量，适用时间有限，所以并没有添加

![image](https://user-images.githubusercontent.com/67408027/99680785-61515000-2ab8-11eb-91ce-0e154da1c38d.png)
这个地方23行“Upgrader"应该是”Harvester"，笔误了吧
以及如果要生成claimer占领其他房间应该怎么做呢，我没找到这块的代码

**Comment by JesseTzh** [comment]
> > > 您的代码看起来很棒！我有个问题，为什么不用container配合无carry组件的creep挖矿呢？Harvest采矿后掉落自动被container收集，仅由mover转运。这样效率似乎更高。
> > > 如果您的代码中有相应设置请麻烦告知一下，谢谢！
> > 
> > 
> > 这种方法在前期不失为一个好选择，但是后期总归要使用Link传输能量，适用时间有限，所以并没有添加
> 
> ![image](https://user-images.githubusercontent.com/67408027/99680785-61515000-2ab8-11eb-91ce-0e154da1c38d.png)
> 这个地方23行“Upgrader"应该是”Harvester"，笔误了吧
> 以及如果要生成claimer占领其他房间应该怎么做呢，我没找到这块的代码



> > > 您的代码看起来很棒！我有个问题，为什么不用container配合无carry组件的creep挖矿呢？Harvest采矿后掉落自动被container收集，仅由mover转运。这样效率似乎更高。
> > > 如果您的代码中有相应设置请麻烦告知一下，谢谢！
> > 
> > 
> > 这种方法在前期不失为一个好选择，但是后期总归要使用Link传输能量，适用时间有限，所以并没有添加
> 
> ![image](https://user-images.githubusercontent.com/67408027/99680785-61515000-2ab8-11eb-91ce-0e154da1c38d.png)
> 这个地方23行“Upgrader"应该是”Harvester"，笔误了吧
> 以及如果要生成claimer占领其他房间应该怎么做呢，我没找到这块的代码

是打错了，感谢指正。
这个项目还在初期试验阶段，大多数功能都不完善，暂时只写了单房间逻辑
要是想要占领其他房间的逻辑可以参考我另一个项目的方法
https://github.com/JesseTzh/ScreepsCode/blob/master/Role_Colonists.js
